-- Generated from data_generator/source_catalog.py.
-- Physical oracle simulation: 144 source tables.

CREATE TABLE HOTEL_PROPERTY (
    HOTEL_PROPERTY_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE HOTEL_BRAND (
    HOTEL_BRAND_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE HOTEL_REGION (
    HOTEL_REGION_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE PROPERTY_ADDRESS (
    PROPERTY_ADDRESS_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE PROPERTY_CONTACT (
    PROPERTY_CONTACT_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE PROPERTY_AMENITY (
    PROPERTY_AMENITY_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE PROPERTY_AMENITY_ASSIGNMENT (
    PROPERTY_AMENITY_ASSIGNMENT_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE PROPERTY_POLICY (
    PROPERTY_POLICY_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE PROPERTY_CALENDAR (
    PROPERTY_CALENDAR_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE BLACKOUT_DATE (
    BLACKOUT_DATE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE BUILDING (
    BUILDING_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE FLOOR (
    FLOOR_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM (
    ROOM_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM_TYPE (
    ROOM_TYPE_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM_STATUS (
    ROOM_STATUS_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM_STATUS_HISTORY (
    ROOM_STATUS_HISTORY_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM_INVENTORY (
    ROOM_INVENTORY_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM_AMENITY (
    ROOM_AMENITY_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM_AMENITY_ASSIGNMENT (
    ROOM_AMENITY_ASSIGNMENT_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM_FEATURE (
    ROOM_FEATURE_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM_FEATURE_ASSIGNMENT (
    ROOM_FEATURE_ASSIGNMENT_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM_BLOCK (
    ROOM_BLOCK_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM_BLOCK_DETAIL (
    ROOM_BLOCK_DETAIL_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM_OUT_OF_ORDER (
    ROOM_OUT_OF_ORDER_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM_INSPECTION (
    ROOM_INSPECTION_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM_RATE_PLAN (
    ROOM_RATE_PLAN_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM_RATE_RULE (
    ROOM_RATE_RULE_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE ROOM_RATE_CALENDAR (
    ROOM_RATE_CALENDAR_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RATE_SEASON (
    RATE_SEASON_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RATE_PACKAGE (
    RATE_PACKAGE_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RATE_PACKAGE_ITEM (
    RATE_PACKAGE_ITEM_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RATE_RESTRICTION (
    RATE_RESTRICTION_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RATE_OVERRIDE (
    RATE_OVERRIDE_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RATE_TAX_MAPPING (
    RATE_TAX_MAPPING_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RATE_MARKET_SEGMENT (
    RATE_MARKET_SEGMENT_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RATE_PROMOTION (
    RATE_PROMOTION_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RATE_YIELD_RULE (
    RATE_YIELD_RULE_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GUEST (
    GUEST_ID NUMBER(19) PRIMARY KEY,
    EXTERNAL_REFERENCE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GUEST_PROFILE (
    GUEST_PROFILE_ID NUMBER(19) PRIMARY KEY,
    EXTERNAL_REFERENCE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GUEST_ADDRESS (
    GUEST_ADDRESS_ID NUMBER(19) PRIMARY KEY,
    EXTERNAL_REFERENCE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GUEST_PREFERENCE (
    GUEST_PREFERENCE_ID NUMBER(19) PRIMARY KEY,
    EXTERNAL_REFERENCE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GUEST_DOCUMENT (
    GUEST_DOCUMENT_ID NUMBER(19) PRIMARY KEY,
    EXTERNAL_REFERENCE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GUEST_CONTACT (
    GUEST_CONTACT_ID NUMBER(19) PRIMARY KEY,
    EXTERNAL_REFERENCE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GUEST_CONSENT (
    GUEST_CONSENT_ID NUMBER(19) PRIMARY KEY,
    EXTERNAL_REFERENCE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GUEST_NOTE (
    GUEST_NOTE_ID NUMBER(19) PRIMARY KEY,
    EXTERNAL_REFERENCE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GUEST_ALERT (
    GUEST_ALERT_ID NUMBER(19) PRIMARY KEY,
    EXTERNAL_REFERENCE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GUEST_COMPANION (
    GUEST_COMPANION_ID NUMBER(19) PRIMARY KEY,
    EXTERNAL_REFERENCE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GUEST_STAY_HISTORY (
    GUEST_STAY_HISTORY_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    EXTERNAL_REFERENCE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GUEST_MERGE_HISTORY (
    GUEST_MERGE_HISTORY_ID NUMBER(19) PRIMARY KEY,
    EXTERNAL_REFERENCE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE VIP_LEVEL (
    VIP_LEVEL_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESERVATION (
    RESERVATION_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESERVATION_ROOM (
    RESERVATION_ROOM_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    PROPERTY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESERVATION_STATUS_HISTORY (
    RESERVATION_STATUS_HISTORY_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESERVATION_GUEST (
    RESERVATION_GUEST_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    EXTERNAL_REFERENCE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESERVATION_MODIFICATION (
    RESERVATION_MODIFICATION_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESERVATION_CANCELLATION (
    RESERVATION_CANCELLATION_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESERVATION_GUARANTEE (
    RESERVATION_GUARANTEE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESERVATION_DEPOSIT (
    RESERVATION_DEPOSIT_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESERVATION_NOTE (
    RESERVATION_NOTE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESERVATION_ALERT (
    RESERVATION_ALERT_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESERVATION_PACKAGE (
    RESERVATION_PACKAGE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESERVATION_PACKAGE_ITEM (
    RESERVATION_PACKAGE_ITEM_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESERVATION_WAITLIST (
    RESERVATION_WAITLIST_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESERVATION_SOURCE (
    RESERVATION_SOURCE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESERVATION_TRACE (
    RESERVATION_TRACE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE CHECKIN (
    CHECKIN_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE CHECKOUT (
    CHECKOUT_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE KEY_CARD_ASSIGNMENT (
    KEY_CARD_ASSIGNMENT_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE FOLIO (
    FOLIO_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE FOLIO_LINE_ITEM (
    FOLIO_LINE_ITEM_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE FOLIO_ADJUSTMENT (
    FOLIO_ADJUSTMENT_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE FOLIO_TRANSFER (
    FOLIO_TRANSFER_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE PAYMENT_AUTHORIZATION (
    PAYMENT_AUTHORIZATION_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE PAYMENT_CAPTURE (
    PAYMENT_CAPTURE_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE PAYMENT_REVERSAL (
    PAYMENT_REVERSAL_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE PAYMENT_METHOD_TOKEN (
    PAYMENT_METHOD_TOKEN_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE CASHIER_SHIFT (
    CASHIER_SHIFT_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE CASHIER_TRANSACTION (
    CASHIER_TRANSACTION_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE LOYALTY_ACCOUNT (
    LOYALTY_ACCOUNT_ID NUMBER(19) PRIMARY KEY,
    EXTERNAL_REFERENCE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE LOYALTY_TRANSACTION (
    LOYALTY_TRANSACTION_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE LOYALTY_TIER (
    LOYALTY_TIER_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE LOYALTY_REDEMPTION (
    LOYALTY_REDEMPTION_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE LOYALTY_PARTNER (
    LOYALTY_PARTNER_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE LOYALTY_BENEFIT (
    LOYALTY_BENEFIT_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE LOYALTY_TIER_HISTORY (
    LOYALTY_TIER_HISTORY_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE LOYALTY_POINT_EXPIRY (
    LOYALTY_POINT_EXPIRY_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE LOYALTY_PROMOTION (
    LOYALTY_PROMOTION_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE LOYALTY_MEMBER_PREFERENCE (
    LOYALTY_MEMBER_PREFERENCE_ID NUMBER(19) PRIMARY KEY,
    EXTERNAL_REFERENCE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE HOUSEKEEPING_TASK (
    HOUSEKEEPING_TASK_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE HOUSEKEEPING_ASSIGNMENT (
    HOUSEKEEPING_ASSIGNMENT_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE HOUSEKEEPING_EMPLOYEE (
    HOUSEKEEPING_EMPLOYEE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE HOUSEKEEPING_SCHEDULE (
    HOUSEKEEPING_SCHEDULE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE HOUSEKEEPING_STATUS_HISTORY (
    HOUSEKEEPING_STATUS_HISTORY_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE HOUSEKEEPING_INSPECTION (
    HOUSEKEEPING_INSPECTION_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE HOUSEKEEPING_SUPPLY (
    HOUSEKEEPING_SUPPLY_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE HOUSEKEEPING_SUPPLY_USAGE (
    HOUSEKEEPING_SUPPLY_USAGE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE LINEN_INVENTORY (
    LINEN_INVENTORY_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE MINIBAR_CHARGE (
    MINIBAR_CHARGE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE MAINTENANCE_TICKET (
    MAINTENANCE_TICKET_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE MAINTENANCE_WORK_ORDER (
    MAINTENANCE_WORK_ORDER_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE MAINTENANCE_TECHNICIAN (
    MAINTENANCE_TECHNICIAN_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE MAINTENANCE_ASSET (
    MAINTENANCE_ASSET_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE MAINTENANCE_PART (
    MAINTENANCE_PART_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE MAINTENANCE_PART_USAGE (
    MAINTENANCE_PART_USAGE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE PREVENTIVE_MAINTENANCE_PLAN (
    PREVENTIVE_MAINTENANCE_PLAN_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE MAINTENANCE_STATUS_HISTORY (
    MAINTENANCE_STATUS_HISTORY_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE VENDOR (
    VENDOR_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE SERVICE_CONTRACT (
    SERVICE_CONTRACT_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESTAURANT (
    RESTAURANT_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESTAURANT_TABLE (
    RESTAURANT_TABLE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESTAURANT_RESERVATION (
    RESTAURANT_RESERVATION_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESTAURANT_GUEST (
    RESTAURANT_GUEST_ID NUMBER(19) PRIMARY KEY,
    EXTERNAL_REFERENCE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESTAURANT_CHECK (
    RESTAURANT_CHECK_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE RESTAURANT_CHECK_ITEM (
    RESTAURANT_CHECK_ITEM_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE SPA_FACILITY (
    SPA_FACILITY_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE SPA_SERVICE (
    SPA_SERVICE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE SPA_THERAPIST (
    SPA_THERAPIST_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE SPA_BOOKING (
    SPA_BOOKING_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE SPA_BOOKING_SERVICE (
    SPA_BOOKING_SERVICE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE SPA_ROOM (
    SPA_ROOM_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE EVENT_VENUE (
    EVENT_VENUE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE EVENT_BOOKING (
    EVENT_BOOKING_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE EVENT_ATTENDEE (
    EVENT_ATTENDEE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE EVENT_SERVICE (
    EVENT_SERVICE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE EVENT_BILLING (
    EVENT_BILLING_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GROUP_BOOKING (
    GROUP_BOOKING_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GROUP_ROOM_BLOCK (
    GROUP_ROOM_BLOCK_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE CORPORATE_ACCOUNT (
    CORPORATE_ACCOUNT_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    EXTERNAL_REFERENCE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE CORPORATE_RATE_AGREEMENT (
    CORPORATE_RATE_AGREEMENT_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE TRAVEL_AGENT (
    TRAVEL_AGENT_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE CHANNEL_PARTNER (
    CHANNEL_PARTNER_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE PARTNER_COMMISSION (
    PARTNER_COMMISSION_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE TAX_RULE (
    TAX_RULE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE SERVICE_CHARGE (
    SERVICE_CHARGE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE EMPLOYEE_PROPERTY_ASSIGNMENT (
    EMPLOYEE_PROPERTY_ASSIGNMENT_ID NUMBER(19) PRIMARY KEY,
    PROPERTY_CODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE SHIFT (
    SHIFT_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE SCHEDULED_ACTIVITY (
    SCHEDULED_ACTIVITY_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE GENERAL_LEDGER_CODE (
    GENERAL_LEDGER_CODE_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE DAILY_REVENUE_SUMMARY (
    DAILY_REVENUE_SUMMARY_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE NIGHT_AUDIT_RUN (
    NIGHT_AUDIT_RUN_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE CURRENCY (
    CURRENCY_ID NUMBER(19) PRIMARY KEY,
    STATUS VARCHAR2(255),
    ATTRIBUTES_JSON VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE EXCHANGE_RATE (
    EXCHANGE_RATE_ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(18,2),
    CURRENCY_CODE VARCHAR2(255),
    SOURCE_CREATED_AT TIMESTAMP(6),
    SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);
