CREATE ROLE IF NOT EXISTS HOSPITALITY_INGESTION_ROLE;
CREATE ROLE IF NOT EXISTS HOSPITALITY_TRANSFORM_ROLE;
CREATE ROLE IF NOT EXISTS HOSPITALITY_ANALYST_ROLE;

GRANT USAGE ON DATABASE HOSPITALITY_DW TO ROLE HOSPITALITY_INGESTION_ROLE;
GRANT USAGE ON SCHEMA HOSPITALITY_DW.RAW TO ROLE HOSPITALITY_INGESTION_ROLE;
GRANT USAGE ON SCHEMA HOSPITALITY_DW.AUDIT TO ROLE HOSPITALITY_INGESTION_ROLE;
GRANT READ, WRITE ON STAGE HOSPITALITY_DW.RAW.RAW_INGESTION_STAGE TO ROLE HOSPITALITY_INGESTION_ROLE;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA HOSPITALITY_DW.RAW TO ROLE HOSPITALITY_INGESTION_ROLE;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA HOSPITALITY_DW.AUDIT TO ROLE HOSPITALITY_INGESTION_ROLE;
GRANT USAGE ON WAREHOUSE WH_INGESTION TO ROLE HOSPITALITY_INGESTION_ROLE;

GRANT USAGE ON DATABASE HOSPITALITY_DW TO ROLE HOSPITALITY_TRANSFORM_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE HOSPITALITY_DW TO ROLE HOSPITALITY_TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA HOSPITALITY_DW.RAW TO ROLE HOSPITALITY_TRANSFORM_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA HOSPITALITY_DW.STAGING TO ROLE HOSPITALITY_TRANSFORM_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA HOSPITALITY_DW.CORE TO ROLE HOSPITALITY_TRANSFORM_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA HOSPITALITY_DW.MART TO ROLE HOSPITALITY_TRANSFORM_ROLE;
GRANT USAGE ON WAREHOUSE WH_TRANSFORM TO ROLE HOSPITALITY_TRANSFORM_ROLE;

GRANT USAGE ON DATABASE HOSPITALITY_DW TO ROLE HOSPITALITY_ANALYST_ROLE;
GRANT USAGE ON SCHEMA HOSPITALITY_DW.CORE TO ROLE HOSPITALITY_ANALYST_ROLE;
GRANT USAGE ON SCHEMA HOSPITALITY_DW.MART TO ROLE HOSPITALITY_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA HOSPITALITY_DW.CORE TO ROLE HOSPITALITY_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA HOSPITALITY_DW.MART TO ROLE HOSPITALITY_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE WH_ANALYTICS TO ROLE HOSPITALITY_ANALYST_ROLE;

