// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/actions" | "/agent" | "/evidence/[evidenceId]" | "/incidents" | "/investigations" | "/map-flows" | "/monitoring" | "/objects-flows" | "/project-design" | "/reconciliation" | "/register-project" | "/settings/ai" | "/test-plan"
type AppRouteHandlerRoutes = "/api/actions" | "/api/agent" | "/api/agent/verify" | "/api/ai-provider" | "/api/ai-reviews" | "/api/data-onboarding" | "/api/demo/readiness" | "/api/evidence/[evidenceId]" | "/api/investigations" | "/api/monitoring" | "/api/monitoring/recovery" | "/api/monitoring/runs/[runId]" | "/api/monitoring/runs/[runId]/[operation]" | "/api/monitoring/runs/[runId]/pipeline-evidence" | "/api/monitoring/runs/[runId]/quality-check" | "/api/onboarding" | "/api/operations" | "/api/project-analysis" | "/api/project-analysis/source/[assetId]" | "/api/project-bootstrap" | "/api/quality-incidents" | "/api/quality-plans" | "/api/quality-plans/runs/[runId]" | "/api/reconciliation" | "/api/workspace"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/actions": {}
  "/agent": {}
  "/api/actions": {}
  "/api/agent": {}
  "/api/agent/verify": {}
  "/api/ai-provider": {}
  "/api/ai-reviews": {}
  "/api/data-onboarding": {}
  "/api/demo/readiness": {}
  "/api/evidence/[evidenceId]": { "evidenceId": string; }
  "/api/investigations": {}
  "/api/monitoring": {}
  "/api/monitoring/recovery": {}
  "/api/monitoring/runs/[runId]": { "runId": string; }
  "/api/monitoring/runs/[runId]/[operation]": { "runId": string; "operation": string; }
  "/api/monitoring/runs/[runId]/pipeline-evidence": { "runId": string; }
  "/api/monitoring/runs/[runId]/quality-check": { "runId": string; }
  "/api/onboarding": {}
  "/api/operations": {}
  "/api/project-analysis": {}
  "/api/project-analysis/source/[assetId]": { "assetId": string; }
  "/api/project-bootstrap": {}
  "/api/quality-incidents": {}
  "/api/quality-plans": {}
  "/api/quality-plans/runs/[runId]": { "runId": string; }
  "/api/reconciliation": {}
  "/api/workspace": {}
  "/evidence/[evidenceId]": { "evidenceId": string; }
  "/incidents": {}
  "/investigations": {}
  "/map-flows": {}
  "/monitoring": {}
  "/objects-flows": {}
  "/project-design": {}
  "/reconciliation": {}
  "/register-project": {}
  "/settings/ai": {}
  "/test-plan": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
