apiVersion: v1
kind: Secret
metadata:
  name: ade-api-secrets
  namespace: ade
type: Opaque
stringData:
  ADE_API_KEYS_JSON: '<replace-with-api-key-json>'
---
apiVersion: v1
kind: Secret
metadata:
  name: ade-web-secrets
  namespace: ade
type: Opaque
stringData:
  ADE_WEB_USERS_JSON: '<replace-with-web-user-json>'
