#!/usr/bin/env python3
"""Render physical source DDL from the reviewed source catalogs."""

from __future__ import annotations

import argparse
from pathlib import Path

from data_generator.source_catalog import ORACLE_TABLES, POSTGRES_TABLES


def semantic_columns(table: str, dialect: str) -> list[str]:
    text = "VARCHAR2(255)" if dialect == "oracle" else "VARCHAR(255)"
    number = "NUMBER(18,2)" if dialect == "oracle" else "NUMERIC(18,2)"
    date_type = "DATE"
    columns: list[str] = []
    if any(token in table.lower() for token in ("reservation", "booking", "stay")):
        columns += [f"STATUS {text}", f"CHECK_IN_DATE {date_type}", f"CHECK_OUT_DATE {date_type}"]
    if any(token in table.lower() for token in ("payment", "refund", "folio", "rate", "revenue", "transaction")):
        columns += [f"AMOUNT {number}", f"CURRENCY_CODE {text}"]
    if any(token in table.lower() for token in ("guest", "user", "member", "account")):
        columns += [f"EXTERNAL_REFERENCE {text}", f"STATUS {text}"]
    if any(token in table.lower() for token in ("property", "room", "hotel")):
        columns += [f"PROPERTY_CODE {text}", f"STATUS {text}"]
    if not columns:
        columns = [f"STATUS {text}", f"ATTRIBUTES_JSON {text}"]
    # Preserve order but remove repeated semantic names.
    return list(dict.fromkeys(columns))


def render_table(table: str, dialect: str) -> str:
    if dialect == "oracle":
        identifier = table.upper()
        base = [
            f"{identifier}_ID NUMBER(19) PRIMARY KEY",
            *semantic_columns(identifier, dialect),
            "SOURCE_CREATED_AT TIMESTAMP(6)",
            "SOURCE_UPDATED_AT TIMESTAMP(6) NOT NULL",
            "IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL",
        ]
    else:
        identifier = table.lower()
        base = [
            f"{identifier}_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            *[column.lower() for column in semantic_columns(identifier, dialect)],
            "source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP",
            "source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL",
            "is_deleted BOOLEAN DEFAULT FALSE NOT NULL",
        ]
    body = ",\n    ".join(base)
    create_clause = "CREATE TABLE" if dialect == "oracle" else "CREATE TABLE IF NOT EXISTS"
    return f"{create_clause} {identifier} (\n    {body}\n);\n"


def render(dialect: str) -> str:
    tables = ORACLE_TABLES if dialect == "oracle" else POSTGRES_TABLES
    heading = (
        "-- Generated from data_generator/source_catalog.py.\n"
        f"-- Physical {dialect} simulation: {len(tables)} source tables.\n\n"
    )
    return heading + "\n".join(render_table(table, dialect) for table in tables)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dialect", choices=["oracle", "postgres", "all"], default="all")
    parser.add_argument("--root", type=Path, default=Path("."))
    args = parser.parse_args()
    dialects = ["oracle", "postgres"] if args.dialect == "all" else [args.dialect]
    for dialect in dialects:
        destination = args.root / "sources" / dialect / "ddl" / "001_source_schema.sql"
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(render(dialect), encoding="utf-8")
        print(f"wrote {destination}")


if __name__ == "__main__":
    main()
