from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any
from agentic_data_platform.models import ApprovalRecord, ExecutionEvidenceRecord, GeneratedArtifactRecord, MigrationPlanRecord, ProjectRecord, RunRecord, RunStepRecord, VerificationReport

class ControlPlaneRepository(ABC):
    @abstractmethod
    def initialize(self) -> None: ...
    @abstractmethod
    def save_project(self, record: ProjectRecord) -> None: ...
    @abstractmethod
    def save_run(self, record: RunRecord) -> None: ...
    @abstractmethod
    def get_run(self, run_id: str) -> RunRecord | None: ...
    @abstractmethod
    def save_run_step(self, record: RunStepRecord) -> None: ...
    @abstractmethod
    def save_artifact(self, record: GeneratedArtifactRecord) -> None: ...
    @abstractmethod
    def save_migration_plan(self, record: MigrationPlanRecord) -> None: ...
    @abstractmethod
    def save_verification_report(self, report: VerificationReport) -> None: ...
    @abstractmethod
    def save_approval(self, record: ApprovalRecord) -> None: ...
    @abstractmethod
    def has_approval(self, run_id: str, scope: str, *, action: str = "execute", environment: str | None = None) -> bool: ...
    @abstractmethod
    def save_execution_evidence(self, record: ExecutionEvidenceRecord) -> None: ...
    @abstractmethod
    def list_records(self, table: str, *, run_id: str | None = None) -> list[dict[str, Any]]: ...
