CREATE PIPE IF NOT EXISTS {{DATABASE}}.RAW.PIPE_PAYMENTS
  AUTO_INGEST = TRUE
  AWS_SNS_TOPIC = '{{SNS_TOPIC_ARN}}'
  COMMENT = 'Auto-ingests payment CSV files from the isolated hospitality prefix'
AS COPY INTO {{DATABASE}}.RAW.PAYMENTS
   FROM @{{DATABASE}}.RAW.STAGE_HOSPITALITY_S3/csv/payments/
   FILE_FORMAT = (FORMAT_NAME = '{{DATABASE}}.RAW.FF_HOSPITALITY_CSV_HEADER')
   PATTERN = '.*[.]csv([.]gz)?$'
   MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
   INCLUDE_METADATA = (_SOURCE_FILE = METADATA$FILENAME, _SOURCE_ROW_NUMBER = METADATA$FILE_ROW_NUMBER, _INGESTED_AT = METADATA$START_SCAN_TIME)
   ON_ERROR = 'SKIP_FILE';
