// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/actions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/actions">> = Specific
  const handler = {} as typeof import("../../app/actions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent">> = Specific
  const handler = {} as typeof import("../../app/agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/evidence/[evidenceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/evidence/[evidenceId]">> = Specific
  const handler = {} as typeof import("../../app/evidence/[evidenceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/incidents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/incidents">> = Specific
  const handler = {} as typeof import("../../app/incidents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/investigations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investigations">> = Specific
  const handler = {} as typeof import("../../app/investigations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/map-flows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/map-flows">> = Specific
  const handler = {} as typeof import("../../app/map-flows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitoring">> = Specific
  const handler = {} as typeof import("../../app/monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/objects-flows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/objects-flows">> = Specific
  const handler = {} as typeof import("../../app/objects-flows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/project-design/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project-design">> = Specific
  const handler = {} as typeof import("../../app/project-design/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reconciliation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reconciliation">> = Specific
  const handler = {} as typeof import("../../app/reconciliation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register-project/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register-project">> = Specific
  const handler = {} as typeof import("../../app/register-project/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/ai">> = Specific
  const handler = {} as typeof import("../../app/settings/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test-plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-plan">> = Specific
  const handler = {} as typeof import("../../app/test-plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/actions">> = Specific
  const handler = {} as typeof import("../../app/api/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent">> = Specific
  const handler = {} as typeof import("../../app/api/agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/verify">> = Specific
  const handler = {} as typeof import("../../app/api/agent/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai-provider/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-provider">> = Specific
  const handler = {} as typeof import("../../app/api/ai-provider/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai-reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-reviews">> = Specific
  const handler = {} as typeof import("../../app/api/ai-reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/data-onboarding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data-onboarding">> = Specific
  const handler = {} as typeof import("../../app/api/data-onboarding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/demo/readiness/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/demo/readiness">> = Specific
  const handler = {} as typeof import("../../app/api/demo/readiness/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/evidence/[evidenceId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evidence/[evidenceId]">> = Specific
  const handler = {} as typeof import("../../app/api/evidence/[evidenceId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/investigations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investigations">> = Specific
  const handler = {} as typeof import("../../app/api/investigations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/monitoring/recovery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/recovery">> = Specific
  const handler = {} as typeof import("../../app/api/monitoring/recovery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/monitoring/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring">> = Specific
  const handler = {} as typeof import("../../app/api/monitoring/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/monitoring/runs/[runId]/[operation]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/runs/[runId]/[operation]">> = Specific
  const handler = {} as typeof import("../../app/api/monitoring/runs/[runId]/[operation]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/monitoring/runs/[runId]/pipeline-evidence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/runs/[runId]/pipeline-evidence">> = Specific
  const handler = {} as typeof import("../../app/api/monitoring/runs/[runId]/pipeline-evidence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/monitoring/runs/[runId]/quality-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/runs/[runId]/quality-check">> = Specific
  const handler = {} as typeof import("../../app/api/monitoring/runs/[runId]/quality-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/monitoring/runs/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/runs/[runId]">> = Specific
  const handler = {} as typeof import("../../app/api/monitoring/runs/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/operations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operations">> = Specific
  const handler = {} as typeof import("../../app/api/operations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/project-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/project-analysis">> = Specific
  const handler = {} as typeof import("../../app/api/project-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/project-analysis/source/[assetId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/project-analysis/source/[assetId]">> = Specific
  const handler = {} as typeof import("../../app/api/project-analysis/source/[assetId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/project-bootstrap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/project-bootstrap">> = Specific
  const handler = {} as typeof import("../../app/api/project-bootstrap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/quality-incidents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality-incidents">> = Specific
  const handler = {} as typeof import("../../app/api/quality-incidents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/quality-plans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality-plans">> = Specific
  const handler = {} as typeof import("../../app/api/quality-plans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/quality-plans/runs/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality-plans/runs/[runId]">> = Specific
  const handler = {} as typeof import("../../app/api/quality-plans/runs/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reconciliation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reconciliation">> = Specific
  const handler = {} as typeof import("../../app/api/reconciliation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace">> = Specific
  const handler = {} as typeof import("../../app/api/workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
