-- TESTBED-ONLY MUTATION.
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.RAW;
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.CDC;
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.STAGING;
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.CORE;
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.MARTS;
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.QUALITY;
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.OPS;
