-- Explicit positional format retained for COPY validation and producer-contract inspection.
CREATE FILE FORMAT IF NOT EXISTS {{DATABASE}}.RAW.FF_HOSPITALITY_CSV
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null', '\\N')
  EMPTY_FIELD_AS_NULL = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
  COMPRESSION = AUTO
  TIMESTAMP_FORMAT = 'AUTO'
  DATE_FORMAT = 'AUTO'
  ENCODING = 'UTF8';

-- Snowflake prohibits SKIP_HEADER with PARSE_HEADER=TRUE. This companion format is
-- used by the actual metadata-driven name-mapped loads and skips the parsed header.
CREATE FILE FORMAT IF NOT EXISTS {{DATABASE}}.RAW.FF_HOSPITALITY_CSV_HEADER
  TYPE = CSV
  FIELD_DELIMITER = ','
  PARSE_HEADER = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null', '\\N')
  EMPTY_FIELD_AS_NULL = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
  COMPRESSION = AUTO
  TIMESTAMP_FORMAT = 'AUTO'
  DATE_FORMAT = 'AUTO'
  ENCODING = 'UTF8';

CREATE FILE FORMAT IF NOT EXISTS {{DATABASE}}.RAW.FF_HOSPITALITY_PARQUET
  TYPE = PARQUET
  COMPRESSION = AUTO
  BINARY_AS_TEXT = FALSE
  USE_LOGICAL_TYPE = TRUE
  TRIM_SPACE = FALSE
  REPLACE_INVALID_CHARACTERS = FALSE;
