-- All source files contain _LOAD_ID and _GENERATION_ID. COPY adds the other metadata fields.
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.HOTELS (
  HOTEL_ID VARCHAR, HOTEL_NAME VARCHAR, BRAND VARCHAR, CITY VARCHAR, STATE VARCHAR, COUNTRY VARCHAR,
  TIMEZONE VARCHAR, OPENED_DATE DATE, ROOM_COUNT NUMBER, ACTIVE BOOLEAN,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.ROOMS (
  ROOM_ID VARCHAR, HOTEL_ID VARCHAR, ROOM_TYPE_ID VARCHAR, ROOM_NUMBER VARCHAR, FLOOR_NUMBER NUMBER, STATUS VARCHAR,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.ROOM_TYPES (
  ROOM_TYPE_ID VARCHAR, HOTEL_ID VARCHAR, TYPE_NAME VARCHAR, MAX_OCCUPANCY NUMBER, BASE_RATE NUMBER(12,2), BED_TYPE VARCHAR,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.GUESTS (
  GUEST_ID VARCHAR, FIRST_NAME VARCHAR, LAST_NAME VARCHAR, EMAIL VARCHAR, COUNTRY VARCHAR, CREATED_AT TIMESTAMP_TZ, MARKETING_OPT_IN BOOLEAN,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.RESERVATIONS (
  RESERVATION_ID VARCHAR, HOTEL_ID VARCHAR, GUEST_ID VARCHAR, ROOM_ID VARCHAR, CHANNEL_ID VARCHAR, BOOKING_STATUS VARCHAR,
  BOOKED_AT TIMESTAMP_TZ, CHECKIN_DATE DATE, CHECKOUT_DATE DATE, ADULTS NUMBER, CHILDREN NUMBER, CURRENCY VARCHAR,
  TOTAL_AMOUNT NUMBER(12,2), UPDATED_AT TIMESTAMP_TZ,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.RESERVATION_GUESTS (
  RESERVATION_GUEST_ID VARCHAR, RESERVATION_ID VARCHAR, GUEST_ID VARCHAR, IS_PRIMARY BOOLEAN,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.PAYMENTS (
  PAYMENT_ID VARCHAR, RESERVATION_ID VARCHAR, PAYMENT_TS TIMESTAMP_TZ, PAYMENT_METHOD VARCHAR, PAYMENT_STATUS VARCHAR,
  AMOUNT NUMBER(12,2), CURRENCY VARCHAR,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.FOLIO_CHARGES (
  FOLIO_ID VARCHAR, RESERVATION_ID VARCHAR, CHARGE_TS TIMESTAMP_TZ, CHARGE_TYPE VARCHAR, DESCRIPTION VARCHAR,
  AMOUNT NUMBER(12,2), CURRENCY VARCHAR,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.CANCELLATIONS (
  CANCELLATION_ID VARCHAR, RESERVATION_ID VARCHAR, CANCELLED_AT TIMESTAMP_TZ, REASON VARCHAR, FEE_AMOUNT NUMBER(12,2),
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.REFUNDS (
  REFUND_ID VARCHAR, PAYMENT_ID VARCHAR, RESERVATION_ID VARCHAR, REFUND_TS TIMESTAMP_TZ, AMOUNT NUMBER(12,2), REASON VARCHAR,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.LOYALTY_MEMBERS (
  LOYALTY_ID VARCHAR, GUEST_ID VARCHAR, TIER VARCHAR, POINTS_BALANCE NUMBER, JOINED_DATE DATE,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.PROPERTY_STAFF (
  STAFF_ID VARCHAR, HOTEL_ID VARCHAR, DEPARTMENT VARCHAR, JOB_TITLE VARCHAR, HIRED_DATE DATE, ACTIVE BOOLEAN,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.STAYS (
  STAY_ID VARCHAR, RESERVATION_ID VARCHAR, HOTEL_ID VARCHAR, ROOM_ID VARCHAR, ACTUAL_CHECKIN_AT TIMESTAMP_TZ,
  ACTUAL_CHECKOUT_AT TIMESTAMP_TZ, STAY_STATUS VARCHAR,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.ROOM_INVENTORY (
  INVENTORY_ID VARCHAR, HOTEL_ID VARCHAR, ROOM_TYPE_ID VARCHAR, INVENTORY_DATE DATE, AVAILABLE_ROOMS NUMBER,
  OCCUPIED_ROOMS NUMBER, OUT_OF_SERVICE_ROOMS NUMBER,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.DAILY_RATES (
  RATE_ID VARCHAR, HOTEL_ID VARCHAR, ROOM_TYPE_ID VARCHAR, RATE_DATE DATE, RATE_PLAN VARCHAR, NIGHTLY_RATE NUMBER(12,2), CURRENCY VARCHAR,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.CHANNEL_BOOKINGS (
  CHANNEL_BOOKING_ID VARCHAR, RESERVATION_ID VARCHAR, CHANNEL_ID VARCHAR, CHANNEL_REFERENCE VARCHAR,
  COMMISSION_AMOUNT NUMBER(12,2), BOOKED_AT TIMESTAMP_TZ,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.HOUSEKEEPING_EVENTS (
  EVENT_ID VARCHAR, HOTEL_ID VARCHAR, ROOM_ID VARCHAR, EVENT_TYPE VARCHAR, EVENT_TS TIMESTAMP_TZ, STAFF_ID VARCHAR, DURATION_MINUTES NUMBER,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.WEB_BOOKING_EVENTS (
  EVENT_ID VARCHAR, SESSION_ID VARCHAR, GUEST_ID VARCHAR, RESERVATION_ID VARCHAR, EVENT_TYPE VARCHAR, EVENT_TS TIMESTAMP_TZ, CHANNEL_ID VARCHAR,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.GUEST_PREFERENCES (
  PREFERENCE_ID VARCHAR, GUEST_ID VARCHAR, PREFERENCE_TYPE VARCHAR, PREFERENCE_VALUE VARCHAR, UPDATED_AT TIMESTAMP_TZ,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.RAW.PROPERTY_DAILY_METRICS (
  METRIC_ID VARCHAR, HOTEL_ID VARCHAR, METRIC_DATE DATE, AVAILABLE_ROOMS NUMBER, OCCUPIED_ROOMS NUMBER,
  GROSS_REVENUE NUMBER(14,2), CANCELLATIONS NUMBER,
  _LOAD_ID VARCHAR, _GENERATION_ID VARCHAR, _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER NUMBER, _INGESTED_AT TIMESTAMP_LTZ
);
