-- Standard streams preserve INSERT/DELETE and update-pair metadata for explicit CDC tests.
CREATE STREAM IF NOT EXISTS {{DATABASE}}.RAW.STREAM_RESERVATIONS ON TABLE {{DATABASE}}.RAW.RESERVATIONS APPEND_ONLY = FALSE;
CREATE STREAM IF NOT EXISTS {{DATABASE}}.RAW.STREAM_PAYMENTS ON TABLE {{DATABASE}}.RAW.PAYMENTS APPEND_ONLY = FALSE;
CREATE STREAM IF NOT EXISTS {{DATABASE}}.RAW.STREAM_STAYS ON TABLE {{DATABASE}}.RAW.STAYS APPEND_ONLY = FALSE;
CREATE STREAM IF NOT EXISTS {{DATABASE}}.RAW.STREAM_CANCELLATIONS ON TABLE {{DATABASE}}.RAW.CANCELLATIONS APPEND_ONLY = FALSE;
CREATE STREAM IF NOT EXISTS {{DATABASE}}.RAW.STREAM_FOLIO_CHARGES ON TABLE {{DATABASE}}.RAW.FOLIO_CHARGES APPEND_ONLY = FALSE;
