CREATE TABLE IF NOT EXISTS {{DATABASE}}.CDC.RESERVATION_CHANGES (
  CHANGE_ID VARCHAR DEFAULT UUID_STRING(), RESERVATION_ID VARCHAR, ACTION VARCHAR, IS_UPDATE BOOLEAN,
  CHANGE_CAPTURED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), GENERATION_ID VARCHAR, LOAD_ID VARCHAR, PAYLOAD VARIANT
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.CDC.PAYMENT_CHANGES (
  CHANGE_ID VARCHAR DEFAULT UUID_STRING(), PAYMENT_ID VARCHAR, ACTION VARCHAR, IS_UPDATE BOOLEAN,
  CHANGE_CAPTURED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), GENERATION_ID VARCHAR, LOAD_ID VARCHAR, PAYLOAD VARIANT
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.CDC.STAY_CHANGES (
  CHANGE_ID VARCHAR DEFAULT UUID_STRING(), STAY_ID VARCHAR, ACTION VARCHAR, IS_UPDATE BOOLEAN,
  CHANGE_CAPTURED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), GENERATION_ID VARCHAR, LOAD_ID VARCHAR, PAYLOAD VARIANT
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.CDC.CANCELLATION_CHANGES (
  CHANGE_ID VARCHAR DEFAULT UUID_STRING(), CANCELLATION_ID VARCHAR, ACTION VARCHAR, IS_UPDATE BOOLEAN,
  CHANGE_CAPTURED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), GENERATION_ID VARCHAR, LOAD_ID VARCHAR, PAYLOAD VARIANT
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.CDC.FOLIO_CHARGE_CHANGES (
  CHANGE_ID VARCHAR DEFAULT UUID_STRING(), FOLIO_ID VARCHAR, ACTION VARCHAR, IS_UPDATE BOOLEAN,
  CHANGE_CAPTURED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), GENERATION_ID VARCHAR, LOAD_ID VARCHAR, PAYLOAD VARIANT
);
