-- CREATE TASK leaves each task SUSPENDED. run_e2e.py never resumes tasks implicitly.
CREATE TASK IF NOT EXISTS {{DATABASE}}.CDC.TASK_CONSUME_RESERVATIONS
  WAREHOUSE = {{WAREHOUSE}} SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('{{DATABASE}}.RAW.STREAM_RESERVATIONS')
  AS INSERT INTO {{DATABASE}}.CDC.RESERVATION_CHANGES (RESERVATION_ID, ACTION, IS_UPDATE, GENERATION_ID, LOAD_ID, PAYLOAD)
     SELECT RESERVATION_ID, METADATA$ACTION, METADATA$ISUPDATE, _GENERATION_ID, _LOAD_ID,
            OBJECT_CONSTRUCT_KEEP_NULL('hotel_id', HOTEL_ID, 'guest_id', GUEST_ID, 'room_id', ROOM_ID,
              'status', BOOKING_STATUS, 'checkin_date', CHECKIN_DATE, 'checkout_date', CHECKOUT_DATE, 'amount', TOTAL_AMOUNT)
     FROM {{DATABASE}}.RAW.STREAM_RESERVATIONS;

CREATE TASK IF NOT EXISTS {{DATABASE}}.CDC.TASK_CONSUME_PAYMENTS
  WAREHOUSE = {{WAREHOUSE}} SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('{{DATABASE}}.RAW.STREAM_PAYMENTS')
  AS INSERT INTO {{DATABASE}}.CDC.PAYMENT_CHANGES (PAYMENT_ID, ACTION, IS_UPDATE, GENERATION_ID, LOAD_ID, PAYLOAD)
     SELECT PAYMENT_ID, METADATA$ACTION, METADATA$ISUPDATE, _GENERATION_ID, _LOAD_ID,
            OBJECT_CONSTRUCT_KEEP_NULL('reservation_id', RESERVATION_ID, 'status', PAYMENT_STATUS, 'amount', AMOUNT)
     FROM {{DATABASE}}.RAW.STREAM_PAYMENTS;

CREATE TASK IF NOT EXISTS {{DATABASE}}.CDC.TASK_CONSUME_STAYS
  WAREHOUSE = {{WAREHOUSE}} SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('{{DATABASE}}.RAW.STREAM_STAYS')
  AS INSERT INTO {{DATABASE}}.CDC.STAY_CHANGES (STAY_ID, ACTION, IS_UPDATE, GENERATION_ID, LOAD_ID, PAYLOAD)
     SELECT STAY_ID, METADATA$ACTION, METADATA$ISUPDATE, _GENERATION_ID, _LOAD_ID,
            OBJECT_CONSTRUCT_KEEP_NULL('reservation_id', RESERVATION_ID, 'hotel_id', HOTEL_ID, 'room_id', ROOM_ID, 'status', STAY_STATUS)
     FROM {{DATABASE}}.RAW.STREAM_STAYS;

CREATE TASK IF NOT EXISTS {{DATABASE}}.CDC.TASK_CONSUME_CANCELLATIONS
  WAREHOUSE = {{WAREHOUSE}} SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('{{DATABASE}}.RAW.STREAM_CANCELLATIONS')
  AS INSERT INTO {{DATABASE}}.CDC.CANCELLATION_CHANGES (CANCELLATION_ID, ACTION, IS_UPDATE, GENERATION_ID, LOAD_ID, PAYLOAD)
     SELECT CANCELLATION_ID, METADATA$ACTION, METADATA$ISUPDATE, _GENERATION_ID, _LOAD_ID,
            OBJECT_CONSTRUCT_KEEP_NULL('reservation_id', RESERVATION_ID, 'reason', REASON, 'fee_amount', FEE_AMOUNT)
     FROM {{DATABASE}}.RAW.STREAM_CANCELLATIONS;

CREATE TASK IF NOT EXISTS {{DATABASE}}.CDC.TASK_CONSUME_FOLIO_CHARGES
  WAREHOUSE = {{WAREHOUSE}} SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('{{DATABASE}}.RAW.STREAM_FOLIO_CHARGES')
  AS INSERT INTO {{DATABASE}}.CDC.FOLIO_CHARGE_CHANGES (FOLIO_ID, ACTION, IS_UPDATE, GENERATION_ID, LOAD_ID, PAYLOAD)
     SELECT FOLIO_ID, METADATA$ACTION, METADATA$ISUPDATE, _GENERATION_ID, _LOAD_ID,
            OBJECT_CONSTRUCT_KEEP_NULL('reservation_id', RESERVATION_ID, 'charge_type', CHARGE_TYPE, 'amount', AMOUNT)
     FROM {{DATABASE}}.RAW.STREAM_FOLIO_CHARGES;
