CREATE TABLE IF NOT EXISTS {{DATABASE}}.OPS.LOAD_RUNS (
  LOAD_ID VARCHAR, GENERATION_ID VARCHAR, MODE VARCHAR, STATUS VARCHAR, STARTED_AT TIMESTAMP_LTZ,
  COMPLETED_AT TIMESTAMP_LTZ, DETAILS VARIANT
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.OPS.FILE_LOAD_RESULTS (
  LOAD_ID VARCHAR, GENERATION_ID VARCHAR, ENTITY VARCHAR, FILE_NAME VARCHAR, STATUS VARCHAR,
  ROWS_PARSED NUMBER, ROWS_LOADED NUMBER, ERROR_COUNT NUMBER, FIRST_ERROR VARCHAR, RECORDED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.QUALITY.DQ_RESULTS (
  RUN_ID VARCHAR, GENERATION_ID VARCHAR, LOAD_ID VARCHAR, RULE_NAME VARCHAR, LAYER VARCHAR,
  SEVERITY VARCHAR, STATUS VARCHAR, FAILED_ROWS NUMBER, EVIDENCE VARIANT, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.QUALITY.RECONCILIATION_RESULTS (
  RUN_ID VARCHAR, GENERATION_ID VARCHAR, LOAD_ID VARCHAR, ENTITY VARCHAR, GENERATED_ROWS NUMBER,
  COPY_PARSED_ROWS NUMBER, COPY_LOADED_ROWS NUMBER, RAW_ROWS NUMBER, REJECTED_ROWS NUMBER,
  STATUS VARCHAR, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.QUALITY.RCA_RESULTS (
  RUN_ID VARCHAR, GENERATION_ID VARCHAR, LOAD_ID VARCHAR, SCENARIO VARCHAR, EXPECTED_DIVERGENCE VARCHAR,
  OBSERVED_DIVERGENCE VARCHAR, CORRECT BOOLEAN, EVIDENCE VARIANT, ANALYZED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
