CREATE VIEW IF NOT EXISTS {{DATABASE}}.OPS.V_RAW_GENERATION_COUNTS AS
SELECT '_ALL' ENTITY, _GENERATION_ID GENERATION_ID, _LOAD_ID LOAD_ID, COUNT(*) ROW_COUNT, MAX(_INGESTED_AT) LAST_INGESTED_AT
FROM {{DATABASE}}.RAW.RESERVATIONS GROUP BY _GENERATION_ID, _LOAD_ID;

CREATE VIEW IF NOT EXISTS {{DATABASE}}.QUALITY.V_LATEST_DQ_SUMMARY AS
SELECT GENERATION_ID, LOAD_ID,
       COUNT_IF(STATUS = 'PASS') PASSED_RULES,
       COUNT_IF(STATUS = 'FAIL') FAILED_RULES,
       MAX(CHECKED_AT) CHECKED_AT
FROM {{DATABASE}}.QUALITY.DQ_RESULTS
GROUP BY GENERATION_ID, LOAD_ID;

CREATE VIEW IF NOT EXISTS {{DATABASE}}.QUALITY.V_LATEST_RECONCILIATION AS
SELECT * FROM {{DATABASE}}.QUALITY.RECONCILIATION_RESULTS
QUALIFY ROW_NUMBER() OVER (PARTITION BY GENERATION_ID, LOAD_ID, ENTITY ORDER BY CHECKED_AT DESC) = 1;
