GRANT USAGE ON INTEGRATION {{STORAGE_INTEGRATION}} TO ROLE {{ROLE}};
GRANT USAGE ON STAGE {{DATABASE}}.RAW.STAGE_HOSPITALITY_S3 TO ROLE {{ROLE}};
GRANT MONITOR ON PIPE {{DATABASE}}.RAW.PIPE_RESERVATIONS TO ROLE {{ROLE}};
GRANT MONITOR ON PIPE {{DATABASE}}.RAW.PIPE_PAYMENTS TO ROLE {{ROLE}};
GRANT MONITOR ON PIPE {{DATABASE}}.RAW.PIPE_FOLIO_CHARGES TO ROLE {{ROLE}};
GRANT MONITOR ON PIPE {{DATABASE}}.RAW.PIPE_CANCELLATIONS TO ROLE {{ROLE}};
GRANT MONITOR ON PIPE {{DATABASE}}.RAW.PIPE_STAYS TO ROLE {{ROLE}};
GRANT MONITOR ON PIPE {{DATABASE}}.RAW.PIPE_CHANNEL_BOOKINGS TO ROLE {{ROLE}};
