CREATE ROLE IF NOT EXISTS {{ROLE}} COMMENT = 'Least-privilege role for the isolated hospitality testbed';
GRANT USAGE ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{ROLE}};
GRANT USAGE ON DATABASE {{DATABASE}} TO ROLE {{ROLE}};
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{DATABASE}} TO ROLE {{ROLE}};
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE PIPE, CREATE STREAM, CREATE TASK
  ON ALL SCHEMAS IN DATABASE {{DATABASE}} TO ROLE {{ROLE}};
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE {{DATABASE}} TO ROLE {{ROLE}};
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE {{DATABASE}} TO ROLE {{ROLE}};
GRANT SELECT ON ALL VIEWS IN DATABASE {{DATABASE}} TO ROLE {{ROLE}};
GRANT SELECT ON FUTURE VIEWS IN DATABASE {{DATABASE}} TO ROLE {{ROLE}};
GRANT READ, WRITE ON STAGE {{DATABASE}}.RAW.STAGE_HOSPITALITY_INTERNAL TO ROLE {{ROLE}};
