hospitality_testbed:
  target: testbed
  outputs:
    testbed:
      type: snowflake
      account: "{{ env_var('ADE_SNOWFLAKE_ACCOUNT', 'not-used-by-dbt-parse') }}"
      user: "{{ env_var('ADE_SNOWFLAKE_USER', 'not-used-by-dbt-parse') }}"
      password: "{{ env_var('ADE_SNOWFLAKE_PASSWORD', 'not-used-by-dbt-parse') }}"
      role: "{{ env_var('ADE_SNOWFLAKE_ROLE', 'ADE_HOSPITALITY_TESTBED_ROLE') }}"
      database: "{{ env_var('ADE_SNOWFLAKE_DATABASE', 'HOSPITALITY_TESTBED') }}"
      warehouse: "{{ env_var('ADE_SNOWFLAKE_WAREHOUSE', 'ADE_HOSPITALITY_TESTBED_WH') }}"
      schema: STAGING
      threads: 4

