-- Run as a role allowed to create databases, warehouses, schemas, and roles.
CREATE DATABASE IF NOT EXISTS HOSPITALITY_DW;

CREATE SCHEMA IF NOT EXISTS HOSPITALITY_DW.RAW;
CREATE SCHEMA IF NOT EXISTS HOSPITALITY_DW.STAGING;
CREATE SCHEMA IF NOT EXISTS HOSPITALITY_DW.CORE;
CREATE SCHEMA IF NOT EXISTS HOSPITALITY_DW.MART;
CREATE SCHEMA IF NOT EXISTS HOSPITALITY_DW.AUDIT;
CREATE SCHEMA IF NOT EXISTS HOSPITALITY_DW.UTIL;

CREATE WAREHOUSE IF NOT EXISTS WH_INGESTION
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS WH_TRANSFORM
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS WH_ANALYTICS
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE FILE FORMAT HOSPITALITY_DW.RAW.FF_CSV
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', 'NULL', 'null')
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE OR REPLACE FILE FORMAT HOSPITALITY_DW.RAW.FF_JSON
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

CREATE OR REPLACE FILE FORMAT HOSPITALITY_DW.RAW.FF_PARQUET
  TYPE = PARQUET
  USE_LOGICAL_TYPE = TRUE;

CREATE STAGE IF NOT EXISTS HOSPITALITY_DW.RAW.RAW_INGESTION_STAGE
  DIRECTORY = (ENABLE = TRUE);

CREATE TABLE IF NOT EXISTS HOSPITALITY_DW.RAW.RAW_INGESTION_EVENTS (
  RAW_RECORD_ID VARCHAR NOT NULL,
  SOURCE_SYSTEM VARCHAR NOT NULL,
  SOURCE_TABLE VARCHAR NOT NULL,
  SOURCE_FILE_NAME VARCHAR,
  SOURCE_PRIMARY_KEY VARCHAR,
  INGESTION_BATCH_ID VARCHAR NOT NULL,
  INGESTED_AT TIMESTAMP_TZ NOT NULL,
  SOURCE_CREATED_AT TIMESTAMP_TZ,
  SOURCE_UPDATED_AT TIMESTAMP_TZ,
  RECORD_HASH VARCHAR NOT NULL,
  RAW_PAYLOAD VARIANT,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  CONSTRAINT PK_RAW_INGESTION_EVENTS PRIMARY KEY (RAW_RECORD_ID) NOT ENFORCED
)
CLUSTER BY (SOURCE_SYSTEM, SOURCE_TABLE, TO_DATE(INGESTED_AT));

CREATE TABLE IF NOT EXISTS HOSPITALITY_DW.RAW.REJECTED_RECORDS (
  REJECTION_ID VARCHAR DEFAULT UUID_STRING(),
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_SYSTEM VARCHAR,
  SOURCE_OBJECT VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  ROW_NUMBER NUMBER,
  RAW_PAYLOAD VARIANT,
  ERROR_CODE VARCHAR,
  ERROR_MESSAGE VARCHAR,
  REJECTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

