CREATE TABLE IF NOT EXISTS HOSPITALITY_DW.AUDIT.BATCH_CONTROL (
  BATCH_ID VARCHAR PRIMARY KEY NOT ENFORCED,
  DAG_ID VARCHAR NOT NULL,
  RUN_ID VARCHAR,
  SOURCE_SYSTEM VARCHAR NOT NULL,
  SCHEDULED_FOR TIMESTAMP_TZ,
  STARTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  COMPLETED_AT TIMESTAMP_TZ,
  BATCH_STATUS VARCHAR NOT NULL,
  ERROR_COUNT NUMBER DEFAULT 0,
  CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS HOSPITALITY_DW.AUDIT.LOAD_HISTORY (
  LOAD_ID VARCHAR PRIMARY KEY NOT ENFORCED,
  BATCH_ID VARCHAR NOT NULL,
  DAG_ID VARCHAR NOT NULL,
  SOURCE_SYSTEM VARCHAR NOT NULL,
  SOURCE_OBJECT VARCHAR NOT NULL,
  TARGET_OBJECT VARCHAR NOT NULL,
  LOAD_STRATEGY VARCHAR,
  WATERMARK_START VARCHAR,
  WATERMARK_END VARCHAR,
  LOAD_STATUS VARCHAR NOT NULL,
  SOURCE_ROW_COUNT NUMBER,
  TARGET_ROW_COUNT NUMBER,
  REJECTED_ROW_COUNT NUMBER DEFAULT 0,
  STARTED_AT TIMESTAMP_TZ NOT NULL,
  COMPLETED_AT TIMESTAMP_TZ,
  QUERY_ID VARCHAR
);

CREATE TABLE IF NOT EXISTS HOSPITALITY_DW.AUDIT.TABLE_WATERMARKS (
  SOURCE_SYSTEM VARCHAR NOT NULL,
  SOURCE_OBJECT VARCHAR NOT NULL,
  WATERMARK_COLUMN VARCHAR NOT NULL,
  WATERMARK_VALUE VARCHAR,
  LAST_SUCCESSFUL_BATCH_ID VARCHAR,
  UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT UK_TABLE_WATERMARK UNIQUE (SOURCE_SYSTEM, SOURCE_OBJECT) NOT ENFORCED
);

CREATE TABLE IF NOT EXISTS HOSPITALITY_DW.AUDIT.DATA_QUALITY_RESULTS (
  RESULT_ID VARCHAR DEFAULT UUID_STRING(),
  BATCH_ID VARCHAR,
  CHECK_NAME VARCHAR NOT NULL,
  CHECK_LAYER VARCHAR NOT NULL,
  TARGET_OBJECT VARCHAR NOT NULL,
  EXPECTED_VALUE VARIANT,
  ACTUAL_VALUE VARIANT,
  CHECK_STATUS VARCHAR NOT NULL,
  SEVERITY VARCHAR NOT NULL,
  DETAILS VARIANT,
  CHECKED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS HOSPITALITY_DW.AUDIT.PIPELINE_ERRORS (
  ERROR_ID VARCHAR DEFAULT UUID_STRING(),
  BATCH_ID VARCHAR,
  DAG_ID VARCHAR,
  TASK_ID VARCHAR,
  ERROR_CLASS VARCHAR,
  ERROR_MESSAGE VARCHAR,
  ERROR_CONTEXT VARIANT,
  OCCURRED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  RESOLVED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS HOSPITALITY_DW.AUDIT.DBT_RUN_HISTORY (
  DBT_INVOCATION_ID VARCHAR NOT NULL,
  BATCH_ID VARCHAR,
  COMMAND VARCHAR NOT NULL,
  TARGET_NAME VARCHAR,
  STARTED_AT TIMESTAMP_TZ,
  COMPLETED_AT TIMESTAMP_TZ,
  RUN_STATUS VARCHAR,
  RESULTS VARIANT,
  RECORDED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

