#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="$ROOT/docker-compose.local.yml"
ENV_FILE="${ADE_LOCAL_ENV_FILE:-$ROOT/.env.local}"

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "$1 is required"
}

require_docker() {
  require_command docker
  docker info >/dev/null 2>&1 || fail "Docker is not running"
  docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required"
}

random_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$1"
    return
  fi
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$1" <<'PY'
import secrets
import sys
print(secrets.token_hex(int(sys.argv[1])))
PY
    return
  fi
  fail "openssl or python3 is required to generate local credentials"
}

compose() {
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"
}

init_env() {
  if [[ -f "$ENV_FILE" ]]; then
    echo "Using existing $ENV_FILE"
    return
  fi

  umask 077
  local api_token commit_sha
  api_token="$(random_hex 32)"
  commit_sha="$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || printf 'local')"

  cat >"$ENV_FILE" <<EOF
# Generated by scripts/ade-local.sh. Keep this file private and uncommitted.
ADE_API_BIND=127.0.0.1
ADE_API_PORT=8001
ADE_WEB_BIND=127.0.0.1
ADE_WEB_PORT=3000
ADE_COMMIT_SHA=$commit_sha
ADE_API_SERVICE_TOKEN=$api_token
ADE_API_KEYS_JSON='{"local-admin":{"token":"$api_token","subject":"local-admin","role":"admin"}}'
EOF
  chmod 600 "$ENV_FILE" 2>/dev/null || true
  echo "Created $ENV_FILE"
  echo "The local API credential is stored only in $ENV_FILE"
}

load_env() {
  [[ -f "$ENV_FILE" ]] || init_env
  # Generated values contain only controlled keys and random hexadecimal secrets.
  # shellcheck disable=SC1090
  source "$ENV_FILE"
}

wait_for_url() {
  local label="$1" url="$2" attempts="${3:-60}"
  require_command curl
  for ((i=1; i<=attempts; i++)); do
    if curl --fail --silent --show-error --max-time 3 "$url" >/dev/null 2>&1; then
      echo "$label is healthy: $url"
      return
    fi
    sleep 2
  done
  compose ps || true
  compose logs --tail=120 || true
  fail "$label did not become healthy: $url"
}

smoke() {
  require_docker
  load_env
  require_command curl

  local api_base="http://${ADE_API_BIND:-127.0.0.1}:${ADE_API_PORT:-8001}"
  local web_base="http://${ADE_WEB_BIND:-127.0.0.1}:${ADE_WEB_PORT:-3000}"
  local unauth_status direct_payload proxy_payload

  curl --fail --silent --show-error "$api_base/healthz" >/dev/null
  curl --fail --silent --show-error "$web_base/api/healthz" >/dev/null

  unauth_status="$(curl --silent --output /dev/null --write-out '%{http_code}' \
    "$api_base/api/v1/agents/roster")"
  [[ "$unauth_status" == "401" ]] \
    || fail "API fail-closed check expected HTTP 401 without a bearer token; got $unauth_status"

  direct_payload="$(curl --fail --silent --show-error \
    -H "Authorization: Bearer ${ADE_API_SERVICE_TOKEN}" \
    "$api_base/api/v1/agents/roster")"
  printf '%s' "$direct_payload" | grep -q '"status":"PASS"' \
    || fail "authenticated direct API smoke did not return PASS"

  proxy_payload="$(curl --fail --silent --show-error \
    "$web_base/api/ade/api/v1/agents/roster")"
  printf '%s' "$proxy_payload" | grep -q '"status":"PASS"' \
    || fail "web-to-API proxy smoke did not return PASS"

  echo "PASS: health checks, fail-closed API auth, bearer auth, and web-to-API proxy"
}

up() {
  require_docker
  load_env
  compose config --quiet
  compose up --build -d

  wait_for_url "ADE API" "http://${ADE_API_BIND:-127.0.0.1}:${ADE_API_PORT:-8001}/healthz"
  wait_for_url "ADE web" "http://${ADE_WEB_BIND:-127.0.0.1}:${ADE_WEB_PORT:-3000}/api/healthz"
  smoke

  echo
  echo "ADE is running locally: http://${ADE_WEB_BIND:-127.0.0.1}:${ADE_WEB_PORT:-3000}"
  echo "Credentials: $ENV_FILE"
}

down() {
  require_docker
  [[ -f "$ENV_FILE" ]] || fail "$ENV_FILE does not exist; nothing to stop"
  compose down --remove-orphans
  echo "ADE stopped. Persistent volumes were retained."
}

reset() {
  require_docker
  [[ -f "$ENV_FILE" ]] || fail "$ENV_FILE does not exist; nothing to reset"
  compose down --volumes --remove-orphans
  echo "ADE stopped and local ADE volumes were deleted."
}

status() {
  require_docker
  [[ -f "$ENV_FILE" ]] || fail "$ENV_FILE does not exist; run init first"
  compose ps
}

logs() {
  require_docker
  [[ -f "$ENV_FILE" ]] || fail "$ENV_FILE does not exist; run init first"
  compose logs --tail=200 -f
}

config() {
  require_docker
  load_env
  compose config --quiet
  echo "PASS: docker-compose.local.yml is valid"
}

usage() {
  cat <<'EOF'
Usage: bash scripts/ade-local.sh <command>

Commands:
  init    Generate a gitignored local API credential in .env.local
  up      Build, start, health-check, and smoke-test the local ADE stack
  down    Stop the stack without deleting persistent state
  reset   Stop the stack and delete ADE local volumes (destructive)
  status  Show local container status
  logs    Follow API and web logs
  smoke   Verify health, fail-closed API auth, bearer auth, and web-to-API connectivity
  config  Validate the canonical local Compose configuration
EOF
}

case "${1:-}" in
  init) init_env ;;
  up) up ;;
  down) down ;;
  reset) reset ;;
  status) status ;;
  logs) logs ;;
  smoke) smoke ;;
  config) config ;;
  *) usage; exit 2 ;;
esac
