-- Generated from data_generator/source_catalog.py.
-- Physical postgres simulation: 157 source tables.

CREATE TABLE IF NOT EXISTS app_user (
    app_user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_identity (
    user_identity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_credential (
    user_credential_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_session (
    user_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_device (
    user_device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_address (
    user_address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_preference (
    user_preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_consent (
    user_consent_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_role (
    user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS role (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS role_permission (
    role_permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS permission (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_role_assignment (
    user_role_assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS login_attempt (
    login_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS password_reset_token (
    password_reset_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS oauth_connection (
    oauth_connection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS search_request (
    search_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS search_filter (
    search_filter_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS search_result (
    search_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS search_result_rate (
    search_result_rate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS search_suggestion (
    search_suggestion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS recent_search (
    recent_search_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS saved_search (
    saved_search_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS property_view (
    property_view_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_code varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS room_view (
    room_view_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_code varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS rate_view (
    rate_view_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS availability_request (
    availability_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS availability_response (
    availability_response_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS map_interaction (
    map_interaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS comparison_list (
    comparison_list_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS booking_cart (
    booking_cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    check_in_date date,
    check_out_date date,
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS booking_cart_item (
    booking_cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    check_in_date date,
    check_out_date date,
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS booking_attempt (
    booking_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    check_in_date date,
    check_out_date date,
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS booking_confirmation (
    booking_confirmation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    check_in_date date,
    check_out_date date,
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS booking_guest (
    booking_guest_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    check_in_date date,
    check_out_date date,
    external_reference varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS booking_contact (
    booking_contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    check_in_date date,
    check_out_date date,
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS booking_change (
    booking_change_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    check_in_date date,
    check_out_date date,
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS booking_cancellation (
    booking_cancellation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    check_in_date date,
    check_out_date date,
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS booking_status_event (
    booking_status_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    check_in_date date,
    check_out_date date,
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS booking_price_breakdown (
    booking_price_breakdown_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    check_in_date date,
    check_out_date date,
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS booking_tax (
    booking_tax_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    check_in_date date,
    check_out_date date,
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS booking_fee (
    booking_fee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    check_in_date date,
    check_out_date date,
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS booking_addon (
    booking_addon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    check_in_date date,
    check_out_date date,
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS booking_note (
    booking_note_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    check_in_date date,
    check_out_date date,
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_method (
    payment_method_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_method_token (
    payment_method_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_transaction (
    payment_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_authorization (
    payment_authorization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_capture (
    payment_capture_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_failure (
    payment_failure_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_settlement (
    payment_settlement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_settlement_item (
    payment_settlement_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_dispute (
    payment_dispute_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_chargeback (
    payment_chargeback_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_gateway_event (
    payment_gateway_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS refund_transaction (
    refund_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS refund_status_event (
    refund_status_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS wallet (
    wallet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS wallet_transaction (
    wallet_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS gift_card (
    gift_card_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS gift_card_transaction (
    gift_card_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS promo_code (
    promo_code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS promo_campaign (
    promo_campaign_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS promo_campaign_rule (
    promo_campaign_rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS promo_redemption (
    promo_redemption_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS promo_audience (
    promo_audience_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS promo_budget (
    promo_budget_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS promo_channel (
    promo_channel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS coupon_batch (
    coupon_batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS coupon_code (
    coupon_code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS referral_program (
    referral_program_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS referral_event (
    referral_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS referral_reward (
    referral_reward_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS price_experiment (
    price_experiment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS guest_review (
    guest_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS review_response (
    review_response_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS review_photo (
    review_photo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS review_helpful_vote (
    review_helpful_vote_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS review_flag (
    review_flag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS review_moderation (
    review_moderation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS review_invitation (
    review_invitation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS support_ticket (
    support_ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS support_message (
    support_message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS support_attachment (
    support_attachment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS support_category (
    support_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS support_assignment (
    support_assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS support_sla (
    support_sla_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS support_status_event (
    support_status_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_conversation (
    chat_conversation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_message (
    chat_message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS call_request (
    call_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS service_recovery_credit (
    service_recovery_credit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS notification (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS notification_template (
    notification_template_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS notification_preference (
    notification_preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS email_event (
    email_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS email_delivery (
    email_delivery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS sms_event (
    sms_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS push_event (
    push_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS in_app_message (
    in_app_message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS webhook_delivery (
    webhook_delivery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS notification_suppression (
    notification_suppression_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS marketing_campaign (
    marketing_campaign_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS marketing_touchpoint (
    marketing_touchpoint_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS attribution_event (
    attribution_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS ad_spend (
    ad_spend_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS marketing_audience (
    marketing_audience_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS audience_membership (
    audience_membership_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS affiliate_partner (
    affiliate_partner_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS affiliate_click (
    affiliate_click_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS affiliate_conversion (
    affiliate_conversion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS partner_booking_event (
    partner_booking_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    check_in_date date,
    check_out_date date,
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS partner_api_credential (
    partner_api_credential_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS partner_webhook_event (
    partner_webhook_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS fraud_signal (
    fraud_signal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS risk_score (
    risk_score_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS risk_rule (
    risk_rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS risk_rule_result (
    risk_rule_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS device_fingerprint (
    device_fingerprint_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS identity_verification (
    identity_verification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS velocity_check (
    velocity_check_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS blocked_entity (
    blocked_entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS manual_risk_review (
    manual_risk_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS fraud_case (
    fraud_case_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS fraud_case_event (
    fraud_case_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS api_request_log (
    api_request_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS api_client (
    api_client_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS api_key (
    api_key_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS api_rate_limit (
    api_rate_limit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS feature_flag (
    feature_flag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS feature_flag_rule (
    feature_flag_rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS experiment (
    experiment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS experiment_variant (
    experiment_variant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS experiment_assignment (
    experiment_assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS experiment_event (
    experiment_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS mobile_app_event (
    mobile_app_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS mobile_app_crash (
    mobile_app_crash_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS mobile_release (
    mobile_release_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS wishlist (
    wishlist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS wishlist_item (
    wishlist_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS saved_payment_preference (
    saved_payment_preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(18,2),
    currency_code varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS recently_viewed (
    recently_viewed_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS price_alert (
    price_alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS price_alert_event (
    price_alert_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS content_page (
    content_page_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS content_translation (
    content_translation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS property_content (
    property_content_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_code varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS property_media (
    property_media_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_code varchar(255),
    status varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS seo_landing_page (
    seo_landing_page_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS localization_string (
    localization_string_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS job_queue (
    job_queue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS job_run (
    job_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS outbox_event (
    outbox_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS dead_letter_event (
    dead_letter_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS data_export_request (
    data_export_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS privacy_request (
    privacy_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(255),
    attributes_json varchar(255),
    source_created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    source_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL
);
